// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskManagement.Server.Models;

public partial class ActivityLog
{
    public int LogID { get; set; }

    public int? UserID { get; set; }

    public string Action { get; set; }

    public DateTime? ActionTime { get; set; }

    public virtual User User { get; set; }
}