// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskManagement.Server.Models;

public partial class Comment
{
    public int CommentID { get; set; }

    public int? TaskID { get; set; }

    public int? UserID { get; set; }

    public string Content { get; set; }

    public DateTime? CommentDate { get; set; }

    public virtual Task Task { get; set; }

    public virtual User User { get; set; }
}