// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskManagement.Server.Models;

public partial class ConversationParticipant
{
    public int ConversationID { get; set; }

    public int UserID { get; set; }

    public DateTime JoinedAt { get; set; }

    public virtual Conversation Conversation { get; set; }

    public virtual User User { get; set; }
}