// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskManagement.Server.Models;

public partial class Conversation
{
    public int ConversationID { get; set; }

    public string Title { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? LastMessageAt { get; set; }

    public int? DepartmentID { get; set; }

    public virtual ICollection<ConversationParticipant> ConversationParticipants { get; set; } = new List<ConversationParticipant>();

    public virtual Department Department { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();
}