// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskManagement.Server.Models;

public partial class Message
{
    public int MessageID { get; set; }

    public int ConversationID { get; set; }

    public int SenderID { get; set; }

    public int? ReceiverID { get; set; }

    public string Content { get; set; }

    public DateTime SentAt { get; set; }

    public bool IsRead { get; set; }

    public string Status { get; set; }

    public virtual Conversation Conversation { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual User Receiver { get; set; }

    public virtual User Sender { get; set; }
}