// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskManagement.Server.Models;

public partial class Notification
{
    public int NotificationID { get; set; }

    public int? UserID { get; set; }

    public string Message { get; set; }

    public bool? IsRead { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? MessageID { get; set; }

    public virtual Message MessageNavigation { get; set; }

    public virtual User User { get; set; }
}