// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskManagement.Server.Models;

public partial class TaskAssignment
{
    public int AssignmentID { get; set; }

    public int? TaskID { get; set; }

    public int? AssigneeID { get; set; }

    public DateTime? AssignedAt { get; set; }

    public virtual User Assignee { get; set; }

    public virtual Task Task { get; set; }
}