// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskManagement.Server.Models;

public partial class TaskStatistic
{
    public int StatID { get; set; }

    public int? UserID { get; set; }

    public int? TotalTasks { get; set; }

    public int? CompletedTasks { get; set; }

    public int? LateTasks { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User User { get; set; }
}