// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskManagement.Server.Models;

public partial class Task
{
    public int TaskID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? CreatorID { get; set; }

    public int? DepartmentID { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Priority { get; set; }

    public int? StatusID { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? ProjectID { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual User Creator { get; set; }

    public virtual Department Department { get; set; }

    public virtual Project Project { get; set; }

    public virtual TaskStatus Status { get; set; }

    public virtual ICollection<TaskAssignment> TaskAssignments { get; set; } = new List<TaskAssignment>();
}